# Comando Base para main
#     if message.content.lower().startswith(pref + monster + ' yian garuga'):
#        await client.send_message(message.channel,"**Analise de Monstro...**")
#        await client.send_message(message.channel,"https://vignette.wikia.nocookie.net/monsterhunter/images/c/c5/MHRoC-Yian_Garuga_Card_001.jpg")
#        await client.send_message(message.channel,"**```"

class char:

     yiangaruga = ('**```'
                                                  '\n---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Yian Garuga | Em japonês: イャンガルルガ (Iyangaruruga).'
                                                  '\n**Espécie:** Bird Wyvern.'
                                                  '\n**Elemento:** :fire: Fogo.'
                                                  '\n**Status:** :snake: Envenenamento.'
                                                  '\n**Fraqueza:** :droplet: Água.'
                                                  '\n**Movimentação:** Move-se andando normalmente ou Voando.'
                                                  '\n**Ataques:** Frontais bicando, correndo ou jogando bolas de Veneno. Laterais bicando e dando rabadas. Algumas vezes decolando e dando rasantes'
                                                  '\n**Dicas:** Quebre as orelhas com uma Greatsword ou similar, em baixo do pescoço é um ponto cego! Abuse disso para dar o maior dano possivel, mas tome cuidado com ataques giratorios.'
                                                  '\n**Bagagem necessaria:** Potions, Mega-Potions e Antidotos  .'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
                                                  '\nWyvern Tears	    74%'
                                                  '\nGaruga Scale	    25%'
                                                  '\nGaruga Wing	     1%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nGaruga Scale	64%'
                                                  '\nGaruga Shell	28%'
                                                  '\nGaruga Mane   	 7%'
                                                  '\nGaruga Wing	 1%'
                                                  '\n**-------------**'
                                                  '\n**--- Rabo ---**'
                                                  '\nGaruga Tail	80%'
                                                  '\nGaruga Scale	20%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nGaruga Shell x2	90%'
                                                  '\nSharpened Beak	5%'
                                                  '\nGaruga Ear	5%'
                                                  '\n'
                                                  '\n**Recompensas de Feridas:**'
                                                  '\nOrelhas: '
                                                  '\n        Garuga Ear	        80%'
                                                  '\n        Garuga Scale x3	20%'
                                                  '\nBico:'
                                                  '\n        Sharpened Beak	    80%'
                                                  '\n        Garuga Scale x3	20%'
                                                  '\nAsas:'
                                                  '\n        Garuga Wing	    80%'
                                                  '\n        Garuga Shell x2	20%'
                                                  '\nRabo: '
                                                  '\n        Garuga Mane	    80%'
                                                  '\n        Garuga Shell x2	20%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     blueyiankutku = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Blue Yian Kut-Ku | Em japonês: イャンクック (Iyankukku).'
                                                  '\n**Espécie:** Bird Wyvern.'
                                                  '\n**Elemento:** :fire: Fogo.'
                                                  '\n**Status:** :fire: Queimadura.'
                                                  '\n**Fraqueza:** :droplet: Água e :zap: Raio.'
                                                  '\n**Movimentação:** Move-se andando normalmente ou Voando.'
                                                  '\n**Ataques:** Frontais bicando, correndo ou jogando bolas de fogo. Laterais bicando e dando rabadas. Algumas vezes decolando e dando rasantes'
                                                  '\n**Dicas:** Quebre as orelhas com uma Greatsword ou similar, em baixo do pescoço é um ponto cego! Abuse disso para dar o maior dano possivel, mas tome cuidado com ataques giratorios.'
                                                  '\n**Bagagem necessaria:** Nenhuma, Nem mesmo as que a missão lhe proporciona! Afinal é só um Kut-ku :troll: .'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
                                                  '\nWyvern Tears	    74%'
                                                  '\nBlue Kut-Ku Scl	16%'
                                                  '\nKut-Ku Ear	        10%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nBlue Kut-Ku Scl	47%'
                                                  '\nBlue Kut-Ku Shl	35%'
                                                  '\nKut-Ku Webbing	    15%'
                                                  '\nGiant Beak	         3%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nBlue Kut-Ku Shl	36%'
                                                  '\nMed Monster Bone x2	27%'
                                                  '\nScreamer x2	24%'
                                                  '\nFlame Sac	10%'
                                                  '\nGiant Beak	3%'
                                                  '\n'
                                                  '\n**Recompensas de Feridas:**'
                                                  '\nOrelhas:  '
                                                  '\n        Kut-Ku Ear	        50%'
                                                  '\n        Blue Kut-Ku Scl x3	50%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     yiankutku = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Yian Kut-Ku | Em japonês: イャンクック (Iyankukku).'
                                                  '\n**Espécie:** Bird Wyvern.'
                                                  '\n**Elemento:** :fire: Fogo.'
                                                  '\n**Status:** :fire: Queimadura.'
                                                  '\n**Fraqueza:** :droplet: Água (Nas Asas) e :snowflake: Gelo (Na Cabeça).'
                                                  '\n**Movimentação:** Move-se andando normalmente ou Voando.'
                                                  '\n**Ataques:** Frontais bicando, correndo ou jogando bolas de fogo. Laterais bicando e dando rabadas. Algumas vezes decolando e dando rasantes'
                                                  '\n**Dicas:** Quebre as orelhas com uma Greatsword ou similar, em baixo do pescoço é um ponto cego! Abuse disso para dar o maior dano possivel, mas tome cuidado com ataques giratorios.'
                                                  '\n**Bagagem necessaria:** Nenhuma, Nem mesmo as que a missão lhe proporciona! Afinal é só um Kut-ku: :Leo: .'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
                                                  '\nWyvern Tears	74%'
                                                  '\nKut-Ku Scale	16%'
                                                  '\nKut-Ku Ear	    10%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nKut-Ku Shell	40%'
                                                  '\nKut-Ku Webbing	37%'
                                                  '\nKut-Ku Scale	20%'
                                                  '\nGiant Beak	     3%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nKut-Ku Shell	33%'
                                                  '\nScreamer	24%'
                                                  '\nMed Monster Bone x2	20%'
                                                  '\nFlame Sac	20%'
                                                  '\nGiant Beak	3%'
                                                  '\n'
                                                  '\n**Recompensas de Feridas:**'
                                                  '\nOrelhas: '
                                                  '\n        Kut-Ku Ear	        50%'
                                                  '\n        Kut-Ku Scale x3	42%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     gendrome = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Gendrome | Em japonês: ドスゲネポス (Dosugeneposu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum'
                                                  '\n**Status:** :part_alternation_mark: Paralisia.'
                                                  '\n**Fraqueza:** :droplet: Água e :snowflake: Gelo.'
                                                  '\n**Movimentação:** Move-se andando normalmente, dá saltos para frente, atrás, esqueda e direita.'
                                                  '\n**Ataques:** Sempre frontais, Usando as garras ou saltando ( o salto pode causar o Status ).'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Nenhuma, apenas as que a missão lhe proporciona.'
                                                  '\n'
                                                  '\n**Drops:** Nenhum.'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nGendrome Hide	48%'
                                                  '\nParalysis Sac	35%'
                                                  '\nGenprey Scale	15%'
                                                  '\nGendrome Skull	 2%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nGendrome Hide	    56%'
                                                  '\nParalysis Sac x2	39%'
                                                  '\nGendrome Skull	     5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     
     iodrome = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Iodrome | Em japonês: ドスイーオス (Dosuiosu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum.'
                                                  '\n**Status:** :snake: Envenenamento.'
                                                  '\n**Fraqueza:** :zap:  Raio e :droplet: Água.'
                                                  '\n**Movimentação:** Move-se andando normalmente, dá saltos para frente, atrás, esqueda e direita.'
                                                  '\n**Ataques:** Sempre frontais, Usando as garras, Saltando ou cuspindo Veneno.'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Nenhuma, apenas as que a missão lhe proporciona.'
                                                  '\n'
                                                  '\n**Drops:** Nenhum.'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nIodrome Hide	48%'
                                                  '\nPoison Sac 	35%'
                                                  '\nIoprey Scale	15%'
                                                  '\nIodrome Skull	2%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nIodrome Hide	56%'
                                                  '\nPoison Sac x2  39%'
                                                  '\nIodrome Skull	 5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     
     velocidrome = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Velocidrome | Em japonês: ドスランポス (Dosuranposu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum'
                                                  '\n**Status:** Nenhum.'
                                                  '\n**Fraqueza:** :zap:  Raio e :snowflake: Gelo.'
                                                  '\n**Movimentação:** Move-se andando normalmente, dá saltos para frente, atrás, esqueda e direita.'
                                                  '\n**Ataques:** Sempre frontais, Usando as garras ou saltando.'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Nenhuma, apenas as que a missão lhe proporciona.'
                                                  '\n'
                                                  '\n**Drops:** Nenhum.'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nVelocidrome Claw	53%'
                                                  '\nVelocidrome Hide	30%'
                                                  '\nVelociprey Scale	15%'
                                                  '\nVelocidrome Skull	2%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nVelocidrome Hide	56%'
                                                  '\nScreamer x2	    39%'
                                                  '\nVelocidrome Skull	 5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     
     giadrome = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Giadrome | Em japonês: ド ス ギ ア ノ ス (Dosugianosu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** :snowflake: Gelo.'
                                                  '\n**Status:** :snowman: Boneco de Neve.'
                                                  '\n**Fraqueza:** :fire: Fogo.'
                                                  '\n**Movimentação:** Move-se andando normalmente, dá saltos para frente, atrás, esqueda e direita.'
                                                  '\n**Ataques:** Sempre frontais, Usando as garras, Saltando ou cuspindo gelo.'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Nenhuma, apenas as que a missão lhe proporciona.'
                                                  '\n'
                                                  '\n**Drops:** Nenhum.'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nGiadrome Claw	53%'
                                                  '\nGiadrome Hide	30%'
                                                  '\nGiaprey Scale	15%'
                                                  '\nGiadrome Skull	2%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nGiadrome Hide	56%'
                                                  '\nScreamer x2	39%'
                                                  '\nGiadrome Skull	 5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     gypceros = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Gypceros | Em japonês: ゲ リ ョ ス (Geryosu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum.'
                                                  '\n**Status:**  :snake: Envenenamento e :dizzy: Atordoamento.'
                                                  '\n**Fraqueza:** :fire: Fogo na Cauda.'
                                                  '\n**Movimentação:** Move-se andando normalmente ou Voando.'
                                                  '\n**Ataques:** Frontais bicando, correndo ou jogando bolas de veneno. Laterais bicando e dando rabadas. Algumas vezes decolando e dando rasantes. Batendo o chifre no mesmo e atodoando.'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Antidotos, Não leve shock traps! ele é IMUNE!!.'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nWyvern Tears	74%'
												  '\nPower Extract	20%'
												  '\nLightcrystal	 6%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nRubbery Hide	61%'
                                                  '\nPower Extract	20%'
                                                  '\nPoison Sac		10%'
                                                  '\nLightcrystal	 8%'
                                                  '\nGypceros Head	 1%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nPoison Sac x2		46%'
                                                  '\nPower Extract x2	33%'
                                                  '\nRubbery Hide		20%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nCristal: '
                                                  '\nIron Ore		66%'
                                                  '\nLightcrystal	29%'
                                                  '\nGypceros Head	 5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     purplegypceros = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Purple Gypceros | Em japonês: ゲ リ ョ ス （亜 種） (Geryosu Ashu).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum.'
                                                  '\n**Status:**  :snake: Envenenamento, :skull_crossbones: Envenenamento Nocivo e :dizzy: Atordoamento.'
                                                  '\n**Fraqueza:** :droplet: Agua (1º/2º Gen) e :fire: Fogo (4º Gen).'
                                                  '\n**Movimentação:** Move-se andando normalmente ou Voando.'
                                                  '\n**Ataques:** Frontais bicando, correndo ou jogando bolas de veneno. Laterais bicando e dando rabadas. Algumas vezes decolando e dando rasantes. Batendo o chifre no mesmo e atodoando.'
                                                  '\n**Dicas:** Sempre rolar e atacar lateralmente.'
                                                  '\n**Bagagem necessaria:** Antidotos, Não leve shock traps! ele é IMUNE!!.'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nWyvern Tears	74%'
												  '\nPower Extract	20%'
												  '\nLightcrystal	 6%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nPur Rubbery Hide	61%'
                                                  '\nPower Extract		20%'
                                                  '\nPoison Sac			10%'
                                                  '\nLightcrystal		 8%'
                                                  '\nGypceros Head		 1%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nPoison Sac x2		46%'
                                                  '\nPower Extract x2	33%'
                                                  '\nRubbery Hide		20%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nCristal: '
                                                  '\nIron Ore		66%'
                                                  '\nLightcrystal	29%'
                                                  '\nGypceros Head	 5%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     hypnocatrice = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Hypnocatrice | Em japonês: ヒ プ ノ ッ ク (Hipunokku).'
                                                  '\n**Espécie:** Bird Wyvern'
                                                  '\n**Elemento:** Nenhum.'
                                                  '\n**Status:**  :zzz: Sono.'
                                                  '\n**Fraqueza:** :fire: Fogo.'
                                                  '\n**Movimentação:** ???'
                                                  '\n**Ataques:** ???'
                                                  '\n**Dicas:** ???'
                                                  '\n**Bagagem necessaria:** Um travesseiro e um cobertor... que? to falando serio!'
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nOrangeHypnoPelt	32%'
												  '\nWyvern Sobs		30%'
												  '\nWyvern Tears		30%'
                                                  '\nHypno Bezoar		 8%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nTop-GrdHypnoClaw	40%'
                                                  '\nOrangeHypnoPelt	32%'
                                                  '\nSleep Sac			24%'
                                                  '\nHypno Bezoar		 4%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nRainbowTailFeath	36%'
                                                  '\nOrangeHypnoPelt x2	28%'
                                                  '\nSleep Sac x2		24%'
                                                  '\nSleepyfish x2		 6%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nBico: '
                                                  '\nHypno Beak		90%'
                                                  '\nSleep Sac x2	10%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     rathian = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Rathian | Em japonês: リ オ レ イ ア (Rioreia).'
                                                  '\n**Espécie:** Flying Wyvern'
                                                  '\n**Elemento:** :fire: Fire.'
                                                  '\n**Status:**  :fire: Queimadura e :snake: Envenenamento.'
                                                  '\n**Fraqueza:** :dragon: Dragão e :zap: Raio.'
                                                  '\n**Movimentação:** Andando normalmente e Voando'
                                                  '\n**Ataques:** Correndo, Dando o "Bixo Piruleta" e Atirando bolas de fogo.'
                                                  '\n**Dicas:** Atordoa-lo usando Flashbomb em sua frente, Esquivar sempre para direita e evitar tomar rabadas'
                                                  '\n**Bagagem necessaria:** Flashbombs e Antidotos '
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nWyvern Tears	74%'
												  '\nRathian Scale	25%'
												  '\nRathian Plate	 1%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nRathian Scale		49%'
                                                  '\nRathian Shell		30%'
                                                  '\nFireWyvern Fluid	10%'
                                                  '\nFlame Sac			 8%'
                                                  '\nRathian Spike		 2%'
                                                  '\nFire Wyvern Marrow	 1%'
                                                  '\n**-------------**'
                                                  '\n**--- Calda ---**'
                                                  '\nRathian Scale		59%'
                                                  '\nRathian Shell		22%'
                                                  '\nRathian Spike		 8%'
                                                  '\nMonster Bone+		 6%'
                                                  '\nRathian Plate		 3%'
                                                  '\nFireWyvrn Marrow	 2%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nRathian Scale x2	52%'
                                                  '\nRathian Shell		36%'
                                                  '\nFireWyvrn Marrow	10%'
                                                  '\nRathian Plate		 2%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nCabeça: '
                                                  '\nRathian Shell	71%'
                                                  '\nRathian Scale	25%'
                                                  '\nRathian Plate	 4%'
                                                  '\nAsas:'
                                                  '\nFire Wyvern Claw	75%'
                                                  '\nWyvern Claw x4		25%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     pinkrathian = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Pink Rathian | Em japonês: リ オ レ イ ア （亜 種） (Rioreia Ashu).'
                                                  '\n**Espécie:** Flying Wyvern'
                                                  '\n**Elemento:** :fire: Fire.'
                                                  '\n**Status:**  :fire: Queimadura e :snake: Envenenamento.'
                                                  '\n**Fraqueza:** :dragon: Dragão e :zap: Raio.'
                                                  '\n**Movimentação:** Andando normalmente e Voando'
                                                  '\n**Ataques:** Correndo, Dando o "Bixo Piruleta" e Atirando bolas de fogo.'
                                                  '\n**Dicas:** Atordoa-lo usando Flashbomb em sua frente, Esquivar sempre para direita e evitar tomar rabadas'
                                                  '\n**Bagagem necessaria:** Flashbombs e Antidotos '
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nWyvern Tears		74%'
												  '\nPnk Rathian Scl	25%'
												  '\nRathian Plate		 1%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nPnk Rathian Scl	49%'
                                                  '\nPnk Rathian Shl	30%'
                                                  '\nFireWyvern Fluid	10%'
                                                  '\nFlame Sac			 6%'
                                                  '\nFire Wyvern Marrow	 3%'
                                                  '\nRathian Spike		 1%'
                                                  '\n**-------------**'
                                                  '\n**--- Calda ---**'
                                                  '\nPnk Rathian Scl	56%'
                                                  '\nPnk Rathian Shl	22%'
                                                  '\nRathian Spike		 8%'
                                                  '\nFireWyvrn Marrow	 7%'
                                                  '\nMonster Bone+		 6%'
                                                  '\nRathian Plate		 1%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nPnk Rathian Scl x2	50%'
                                                  '\nPnk Rathian Shl	36%'
                                                  '\nFireWyvrn Marrow	10%'
                                                  '\nRathian Plate		 4%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nCabeça: '
                                                  '\nPnk Rathian Shl	73%'
                                                  '\nPnk Rathian Scl	25%'
                                                  '\nRathian Plate	 	 4%'
                                                  '\nAsas:'
                                                  '\nFire Wyvern Claw	75%'
                                                  '\nWyvern Claw x4		25%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )
     goldrathian = ('**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
                                                  '\n**Nome:** Pink Rathian | Em japonês: リ オ レ イ ア 希 少 種 (Rioreia Kishou Shu).'
                                                  '\n**Espécie:** Flying Wyvern'
                                                  '\n**Elemento:** :fire: Fire.'
                                                  '\n**Status:**  :fire: Queimadura e :snake: Envenenamento.'
                                                  '\n**Fraqueza:** :droplet: Água e :zap: Raio.'
                                                  '\n**Movimentação:** Andando normalmente e Voando'
                                                  '\n**Ataques:** Correndo, Dando o "Bixo Piruleta" e Atirando bolas de fogo.'
                                                  '\n**Dicas:** Atordoa-lo usando Flashbomb em sua frente, Esquivar sempre para direita e evitar tomar rabadas'
                                                  '\n**Bagagem necessaria:** Flashbombs e Antidotos '
                                                  '\n'
                                                  '\n**Drops:** (Usando Sonic Bomb na sua frente)'
												  '\nWyvern Sobs		36%'
												  '\nWyvern Tears		35%'
												  '\nGold Rathian Scale	25%'
												  '\nRathian Plate		 4%'
                                                  '\n'
                                                  '\n**Carves:** '
                                                  '\n**--- Corpo ---**'
                                                  '\nGold Rathian Scale+	43%'
                                                  '\nGold Rathian Carapace	30%'
                                                  '\nRathian Spike			10%'
                                                  '\nRathian Spike+			10%'
                                                  '\nInferno Sac			 5%'
                                                  '\nFireWyvrn BrnStm		 3%'
                                                  '\n**-------------**'
                                                  '\n**--- Calda ---**'
                                                  '\nGold Rathian Scale+	45%'
                                                  '\nGold Rathian Carapace	30%'
                                                  '\nRathian Spike+			10%'
                                                  '\nRathian Plate			10%'
                                                  '\nRathian Ruby			 5%'
                                                  '\n**-------------**'
                                                  '\n'
                                                  '\n**Recompença de Captura:**'
                                                  '\nGold Rathian Carapace	48%'
                                                  '\nGold Rathian Scale+ x2	30%'
                                                  '\nFire Wyvrn Marrow		 8%'
                                                  '\nFireWyvrn BrnStm		 7%'
                                                  '\n'
                                                  '\n**Recompença de Feridas:**'
                                                  '\nCabeça: '
                                                  '\nGold Rathian Carapace	61%'
                                                  '\nGold Rathian Scale+	35%'
                                                  '\nRathian Ruby			 4%'
                                                  '\nAsas:'
                                                  '\nFire Wyvern Claw x2	75%'
                                                  '\nWyvern Claw x5			25%'
                                                  '\n'
                                                  '\n**```'
                                                  '---------------------------------------------'
                                                  '\n```**'
        )



